[daemon]
port = 7788
pid_file = "/home/nek0/hyperion/var/run/hyperiond.pid"
bin_path = "/home/nek0/hyperion/bin/hyperiond"

[logging]
daemon_level = "debug"
cli_level = "debug"
daemon_file = "/home/nek0/hyperion/var/log/hyperiond.log"
daemon_err = "/home/nek0/hyperion/var/log/hyperiond.err"
