[daemon]
port = 7788
pid_file = "~/hyperion/var/run/hyperiond.pid"
bin_path = "~/hyperion/bin/hyperiond"

[logging]
daemon_level = "debug"
cli_level = "debug"
daemon_file = "~/hyperion/var/log/hyperiond.log"
daemon_err = "~/hyperion/var/log/hyperiond.err"
